import type { ProviderDefinition } from "../../core/types.ts";

import { genericImapActions } from "./actions.ts";

export const nodeOnly = true;

export const provider: ProviderDefinition = {
  service: "generic_imap",
  displayName: "IMAP Mailbox",
  description:
    "Unavailable on Cloudflare Workers. Connect any mailbox that exposes IMAP over implicit TLS on port 993, using an application password.",
  categories: ["Communication", "Productivity"],
  authTypes: ["custom_credential"],
  auth: [
    {
      type: "custom_credential",
      fields: [
        {
          key: "email",
          label: "Email Address",
          inputType: "text",
          required: true,
          secret: false,
          placeholder: "user@example.com",
          description: "The full mailbox address to connect.",
        },
        {
          key: "password",
          label: "Application Password",
          inputType: "password",
          required: true,
          secret: true,
          placeholder: "application password",
          description:
            "An application-specific password generated by the mail provider. Prefer a revocable application password over the account login password.",
        },
        {
          key: "imapHost",
          label: "IMAP Host",
          inputType: "text",
          required: true,
          secret: false,
          placeholder: "imap.example.com",
          description: "The IMAP server hostname, reached over implicit TLS on port 993.",
        },
        {
          key: "smtpHost",
          label: "SMTP Host",
          inputType: "text",
          required: false,
          secret: false,
          placeholder: "smtp.example.com",
          description:
            "The SMTP server hostname, reached over implicit TLS on port 465. Defaults to the IMAP host with the imap prefix replaced by smtp.",
        },
      ],
      testAction: {
        actionName: "list_folders",
        input: {},
      },
    },
  ],
  actions: genericImapActions,
};
