apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-connector.fullname" . }}
  labels:
    {{- include "open-connector.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{- $envName := include "open-connector.configEnvName" $key }}
  {{- if or (eq (printf "%T" $value) "float64") (eq (printf "%T" $value) "int") }}
  {{ $envName }}: {{ $value | int | quote }}
  {{- else }}
  {{ $envName }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.database.enabled (not .Values.database.existingUrlSecret) }}
  OOMOL_CONNECT_DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
  NODE_ENV: production
  PORT: "3000"
  HOST: 0.0.0.0