{{- if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "open-connector.fullname" . }}
  labels:
    {{- include "open-connector.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{ toYaml . }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "open-connector.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /health
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}